config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new

    @posts = Post.where('title LIKE ? OR content LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%") if params[:q]

    respond_to do |format|
      format.html { @posts }
      format.js { @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js { @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js { render :index }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.js { @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js { render :index }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudPost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, remote: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-row">
      <div class="col">
        <%= form.text_field :title, placeholder: 'Título...', class: 'form-control' %>
      </div>
      <div class="col">
        <%= form.text_area :content, placeholder: 'Contenido...', class: 'form-control' %>
      </div>
      <div class="col">
        <%= form.submit 'Submit', class: 'btn btn-success' %>
      </div>
    </div>

<% end %>

app/views/posts/_post.html.erb
<td><%= post.title %></td>
<td><%= post.content %></td>
<td><%= link_to 'Show', post %></td>
<td><%= link_to 'Edit', edit_post_path(post), remote: true %></td>
<td><%= link_to 'Destroy', post, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>

app/views/posts/create.js.erb
document.getElementById('tbody').innerHTML += '<%= j render @post %>'

app/views/posts/edit.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j render 'form' %>'

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="font-weight-bold text-center my-2">Posts</h1>

<h2 class="font-weight-bold">Buscador</h2>
  <%= form_tag(root_path, method: :get, remote: true) do %>
    <%= text_field_tag :q, nil, placeholder: 'Buscar...', class: 'form-control mb-2' %>
    <%= submit_tag 'Buscar', class: 'btn btn-primary' %>
  <% end %>

<h2 class="font-weight-bold mt-5">Crear Nuevo Post</h2>

<%= render 'form' %>

<table class="table table-striped mt-2">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="tbody">
    <% @posts.each do |post| %>
      <tr id="post_<%= post.id %>">
        <%= render post %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/index.js.erb
document.getElementById('tbody').innerHTML = ''
<% @posts.each do |post| %>
    document.getElementById('tbody').innerHTML += '<%= j render post %>'
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/update.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j render @post %>'